Slava
vchamelin/Kurs4ch pull request #2
Opened 2021-05-07 22:09 UTC by vchamelin

2021-05-07 22:09 UTC, vchamelin commented
ок

2021-05-17 20:13 UTC, tshemsedinov requested changes
Use prettier and eslint, see example here: https://github.com/metarhia/metasql

2021-05-17 20:13 UTC, tshemsedinov commented on Html/login.html
> +    <link rel="stylesheet" href="../Css/testStyle.css">
It would be better to use lower case in directory naming
```suggestion
    <link rel="stylesheet" href="../css/testStyle.css">
```

2021-05-17 20:13 UTC, tshemsedinov commented on Html/login.html
> +</html>
Add \n at the end of all files.

2021-05-17 20:13 UTC, tshemsedinov commented on Html/login.html
> +    <!--
Remove commented code before landing to master

2021-05-17 20:13 UTC, tshemsedinov commented on Html/postAnAd.html
> +</html>
Add \n at the end of all files.

2021-05-17 20:13 UTC, tshemsedinov commented on js/post.js
> +    optionsList = document.querySelectorAll(".option");
```suggestion
const selected = document.querySelector(".selected");
const optionsContainer = document.querySelector(".options-container");
const searchBox = document.querySelector(".search-box input");
const optionsList = document.querySelectorAll(".option");
```

2021-05-17 20:13 UTC, tshemsedinov commented on js/post.js
> +        let label = option.firstElementChild.nextElementSibling.innerText.toLowerCase();
```suggestion
        const label = option.firstElementChild.nextElementSibling.innerText.toLowerCase();

```

2021-05-17 20:13 UTC, tshemsedinov commented on js/post.js
> +        if (label.indexOf(searchTerm) != -1) {
!==

2021-05-17 20:13 UTC, tshemsedinov commented on js/post.js
> +            option.style.display = "none";
Combine this using ternary operator

2021-05-17 20:13 UTC, tshemsedinov commented on js/script.js
> +    }
use ternary here

2021-05-17 20:13 UTC, tshemsedinov commented on js/script.js
> +    modalCloseBtn = document.querySelector('[data-close]');
separate const for each identifier

2021-06-02 12:02 UTC, cmertenok commented on Html/login.html
> +    <link rel="stylesheet" href="../Css/testStyle.css">
Мы изменили названия папок

2021-06-02 12:02 UTC, cmertenok commented on Html/login.html
> +</html>
Хорошо, добавили добавили /n

2021-06-02 12:02 UTC, cmertenok commented on Html/login.html
> +    <!--
Удалили комментарии с кодом

2021-06-02 12:02 UTC, cmertenok commented on Html/postAnAd.html
> +</html>
Добавили /n

2021-06-02 12:02 UTC, cmertenok commented on js/post.js
> +    optionsList = document.querySelectorAll(".option");
Сделали отдельные константы, для каждого элемента

2021-06-02 12:02 UTC, cmertenok commented on js/post.js
> +        let label = option.firstElementChild.nextElementSibling.innerText.toLowerCase();
Изменили let на const

2021-06-02 12:02 UTC, cmertenok commented on js/post.js
> +        if (label.indexOf(searchTerm) != -1) {
Сделали сравнение по типам

2021-06-02 12:02 UTC, cmertenok commented on js/post.js
> +            option.style.display = "none";
Ок, переписали на тернарный оператор

2021-06-02 12:02 UTC, cmertenok commented on js/script.js
> +    }
Ок, переписали на тернарный оператор

2021-06-02 12:02 UTC, cmertenok commented on js/script.js
> +    modalCloseBtn = document.querySelector('[data-close]');
Сделали отдельные константы

2021-06-02 12:03 UTC, vchamelin commented
Убрали не точности.

2021-06-02 12:03 UTC, closed without merging